### ISSUE TITLE
After installing using the aur and running, it returns (from terminal) No performance modes set

### ISSUE THREAD

**Issue by Lugas7** [Milkshiift/GoofCord#10]
Sorry if this is the wrong way to ask.
I installed using the AUR and got no errors, when I run from desktop (kde plasma) it starts and closes, when I run from terminal with the executable name 'goofcord' I get:
No performance modes set

Is there some kind of config file I should change?

**Comment by Milkshiift** [comment]
It's not an error, it just tells you that the "performanceMode" config parameter is set to "none".
When I install from AUR, GoofCord works as expected. Can you try to launch GoofCord from an official [AppImage](https://github.com/Milkshiift/GoofCord/releases/tag/v1.2.0)?

**Comment by Lugas7** [comment]
I tried to run the GoofCord-1.2.0-linux-arm64.AppImage even though I run amd64, then I got exec format error, did you mean me to install using the .deb?

**Comment by Lugas7** [comment]
when I run the GoofCord-1.2.0-linux-x86_64.AppImage I get the same thing

**Comment by Milkshiift** [comment]
Delete ~/.config/goofcord and try again

**Comment by Lugas7** [comment]
when I run it after deleting the .config/goofcord recursively, and checking that the directory is deleted the following occurs:

Created missing storage folder
(node:314127) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/home/user/.config/goofcord/storage'
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:314127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:314127) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/home/user/.config/goofcord/storage'
(node:314127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Created missing scripts folder
(node:314127) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/home/user/.config/goofcord/scripts'
(node:314127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
Created missing styles folder
Created missing extensions folder
First run of GoofCord. Starting setup.
Setting up temporary GoofCord settings.

The program doesn't crash after this but I don't see an application appearing.

**Comment by Lugas7** [comment]
I did have electron, I just needed to call electron28 instaed of simply electron. When I ran the following (I wasn't sure weather i should specify path in bin or usr, I treid both, this is what resulted when i tried /usr/bin/goofcord)

$ /usr/lib/electron28/electron --trace-warnings /usr/bin/goofcord
App threw an error during load
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /usr/bin/goofcord
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:125:36)
    at defaultLoad (node:internal/modules/esm/load:89:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /usr/bin/goofcord
    at new NodeError (node:internal/errors:405:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:80:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:125:36)
    at defaultLoad (node:internal/modules/esm/load:89:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34

And when I run "/usr/lib/electron28/electron --trace-warnings goofcord", I get:
Error launching app
Unable to find Electron app at /home/corvus/.config/goofcord

Cannot find module '/home/corvus/.config/goofcord'

**Comment by Lugas7** [comment]
But who knows, for whatever reason it works now, I guess after deleting the config and running it from terminal first, then from desktop somehow puts it in a state that it works (launches at least), thanks for the help!
