### ISSUE TITLE
[BUG] Launch Goofcord on Startup starts electron app instead of goofcord when installed from AUR

### ISSUE THREAD

**Issue by JochemSKuipers** [Milkshiift/GoofCord#12]
### Description
When enabling the start goofcord on startup option, it will start the electron development app instead of goofcord.

### Steps to Reproduce
1. Go to Goofcord settings
2. scroll to the bottom
3. enable the Launch on Startup option
4. restart
### Expected Behavior
Upon enabling the start on startup option and restarting, goofcord should launch.
### Actual Behavior
upon enabling the start on startup option and restarting, the electron app launches and goofcord doesnt

### Environment
- Operating System: EndeavourOS (Arch-Linux) Kernel 6.8.5-zen
- Version: 1.3.2 (aur package)

**Comment by Milkshiift** [comment]
The AUR package uses system's electron executable and not the bundled GoofCord's one, which makes the startup entry point to the empty system electron. I will see if I can change this behavior

**Comment by JochemSKuipers** [comment]
that seems logical. would be great if it could be fixed. right now i just work around it by manuallly putting goofcord into autostart.

**Comment by Chorwacjen** [comment]
i am on the same distro and installed from AUR. Both goofcord and electron launch then, which means my issue is slightly different from yours, however it is still impacted by the same thing.

**Comment by Milkshiift** [comment]
Fixed in 3ecc8272b7ded4bfc6ef054ea9ce1f5275bebe8c
