### ISSUE TITLE
[BUG] Screen Share resolution selection not working

### ISSUE THREAD

**Issue by CogumeloDoZap** [Milkshiift/GoofCord#13]
### Description
Goofcord can't share screen with 1080p or 480p
### Steps to Reproduce
Try share screen with less than 720p(or more)
### Expected Behavior
Share screen with chosen resolution
### Actual Behavior
Screen share is limited to 720p 30fps
### Screenshots
![image-23.png](https://github.com/Milkshiift/GoofCord/assets/95929538/417a8ea7-d632-41d3-a035-9ecf7e2fc99f)

![image-18.png](https://github.com/Milkshiift/GoofCord/assets/95929538/1c924fc4-2746-4d40-b6e1-380311fec5e0)

### Environment
- Operating System:
ArchLinux
Gnome
Wayland

**Comment by Milkshiift** [comment]
Do you use Vencord as a client mod? Do you have "Script loading" enabled?
And can you open DevTools and screenshot contents of the console tab after starting screenshare?

**Comment by CogumeloDoZap** [comment]
script loading is enabled. I'm using vencord as client mod. ![image-16.png](https://github.com/Milkshiift/GoofCord/assets/95929538/b005c1de-de0e-4ea5-959d-ca121f696ae3)

**Comment by Milkshiift** [comment]
Please screenshot the last messages in the console

**Comment by CogumeloDoZap** [comment]
![image-26.png](https://github.com/Milkshiift/GoofCord/assets/95929538/18eaa838-86bf-49a2-833e-06b8f45530ad)

**Comment by Milkshiift** [comment]
The script that manages screenshare quality doesn't load. That happens because of a pretty broken detection system for when Discord is loaded. This is already fixed upstream and will be part of the next release.
I will see if I can make a temporary fix
