### ISSUE TITLE
[REQUEST] Flatpak?

### ISSUE THREAD

**Issue by zqpvr** [Milkshiift/GoofCord#16]
### Description
[Please provide a clear and concise description of the feature you'd like to request.]
I'd like a Flatpak.
### Use Case
[Explain how this feature would be useful to you or your project.]
For OS's like SteamOS, Fedora Silver blue and such.
### Describe alternatives you've considered
[A clear and concise description of any alternative solutions or features you've considered.]

### Additional context
[Add any other context or screenshots about the feature request here.]

**Comment by Milkshiift** [comment]
Already in the works https://github.com/flathub/flathub/pull/5238

**Comment by Milkshiift** [comment]
https://flathub.org/apps/io.github.milkshiift.GoofCord
