### ISSUE TITLE
[REQUEST] Equicord support

### ISSUE THREAD

**Issue by nyabinary** [Milkshiift/GoofCord#18]
### Description
Instead of just offering Vencord support, offer [Equicord](https://github.com/Equicord/Equicord) support as well.

### Use Case
[Equicord](https://github.com/Equicord/Equicord) is a fork of Vencord with more features and plugins

### Describe alternatives you've considered
Continue using Vencord.

**Comment by Milkshiift** [comment]
Added in aeae60b3e765bdb74a71442401e7c2e681936067
For now you can set the client mod to custom and use this link for js:
```https://github.com/Equicord/Equicord/releases/download/latest/browser.js```
And this link for css:
```https://github.com/Equicord/Equicord/releases/download/latest/browser.css```
