### ISSUE TITLE
[REQUEST] Add GoofCord to winget and scoop

### ISSUE THREAD

**Issue by anxshi** [Milkshiift/GoofCord#19]
### Description
This feature request proposes adding GoofCord to the package managers winget **and** scoop.

### Use Case
Including GoofCord in winget and scoop would benefit users in several ways:

- Simplified Installation: Through winget and scoop, users would enjoy a streamlined installation process for GoofCord. These package managers handle dependencies and ensure compatibility, making installation smoother than manual compilation or downloading from unknown sources.
- Accessibility: Having GoofCord in these repositories would increase its accessibility for Windows users, especially those unfamiliar with manual installation methods. Users could easily discover and install GoofCord through familiar package management tools.
- Security: Package managers like winget and scoop often implement security measures to verify package integrity. This can help mitigate risks associated with downloading from untrusted sources.

### Describe alternatives you've considered
None. Users who seek to only use package managers on windows won't be able to install GoofCord.

### Additional context
By adding GoofCord to these repositories, winget and scoop can expand their offerings to cater to users who prioritize privacy-focused alternatives to mainstream applications.

**Comment by Milkshiift** [comment]
Added to winget. `winget install GoofCord`
