### ISSUE TITLE
[BUG] Not logging in.

### ISSUE THREAD

**Issue by Y0L042** [Milkshiift/GoofCord#2]
### Description
[Provide a brief description of the bug you encountered]
GoofCord is not logging me in.

### Steps to Reproduce
I run the installed app and it opens the discord login screen. I enter my email and password, and click login. it shows the 3-dot loading symbol, then goes back to 'Log In', doing nothing. When I scan the QR code using the mobile app, it shows my discord user info on GoofCord: 'Logging in as User...'. On the android app, I select log in as desctop. On GoofCord, my user icon changes to a three-dot loading symbol, before reverting back to the default QR code, not logging me in. On my android, discord shows 'You're in!'.

### Expected Behavior
[Provide a clear and concise description of what you expected to happen]
I expected to be logged in to discord (goofcord), either with email/password, or with qr code scanning.

### Actual Behavior
[Describe what actually happened]
While it looked like the app was loading when i initiated login, it would then revert back to the standard login screen.

### Screenshots
[If applicable, add screenshots that help illustrate the problem]

### Environment
I installed it on Windows 10 Pro 22H2 19045.3208

### Additional Information
[Provide any additional information that might be useful in solving the problem, such as error messages or relevant logs]
I have installed version 0.7.1

**Comment by Y0L042** [comment]
I have now tried version 0.7.0, and it logs in fine (i used qr, did not try email/pswrd on 0.7.0).

**Comment by Milkshiift** [comment]
Thank you for opening an issue. I can replicate this behavior on my machine, will try to release a patch with a fix today.

**Comment by Milkshiift** [comment]
Released 0.7.2, should be fixed
