### ISSUE TITLE
[BUG] Minimize to tray not working

### ISSUE THREAD

**Issue by EditorBryce** [Milkshiift/GoofCord#20]
### Description
[No matter what OS, Linux or Windows, the minimize to tray setting doesn't work. And yes, it's enabled in the settings.]

### Steps to Reproduce
[1) Open Goofcord. 2) Make sure minimize to tray is enabled in settings. 3) Close GoofCord by clicking the X button. 4) Notice that it disappears from system tray, and when you reopen it, the window scaling is back to fullscreen.]

### Expected Behavior
[I expected clicking the X button to minimize GoofCord like the official client, and to open it exactly how it was before I 'minimized' it.]

### Actual Behavior
[GoofCord **completely** closed and did not minimize.]

### Environment
- Operating System: [Windows 11, Linux Mint 21.3]
- Version: [1.4.2]

**Comment by Milkshiift** [comment]
This is only the case when using a native titlebar. You can use a custom one until there is a fix if minimizing to tray is more important

**Comment by Milkshiift** [comment]
Fixed in https://github.com/Milkshiift/GoofCord/commit/744a4de70248eccf163366ebc8b7941846e3bb72
