### ISSUE TITLE
[REQUEST] Option or ability to keep its last window size adjustment

### ISSUE THREAD

**Issue by peterpandemonium** [Milkshiift/GoofCord#22]
### Description
App appears to be defaulted in the maximized window setting at every start-up - and each start-up I constantly have to adjust the window to a certain size of my preference. Was wondering if Goofcord can get the option (or default) to keep the last resize adjustment in every session.

### Use Case
It being able to keep the last resize adjustment to a user's preference would save time.

### Describe alternatives you've considered
-

### Additional context
-

**Comment by Milkshiift** [comment]
Added in https://github.com/Milkshiift/GoofCord/commit/8374859d954c3dc60b97e9cc34736c0a307d4e15
