### ISSUE TITLE
Add a way to have lossless stereo like abaddon has 

### ISSUE THREAD

**Issue by Pickymarker** [Milkshiift/GoofCord#23]
Add a way to have lossless stereo like abaddon has so that people can have perfect stereo quality on discord and make it as lossless as opus can be so have raw mic input/allow for full 16bit gain which is what discord uses and no processing of mic for it to be as lossless as discord can get

**Comment by Milkshiift** [comment]
This is not GoofCord's line of work. What you are describing needs to be done with a client mod plugin.
+ Discord web version uses WebRTC for voice chats instead of their proprietary discord_voice, which limits what you can do pretty substantially
