### ISSUE TITLE
[BUG] Screenshare not working, it just disappears

### ISSUE THREAD

**Issue by CatPieLeaf** [Milkshiift/GoofCord#25]
### Description
The screenshare feature is not working. it just disappears once you start, and nothing happens.

### Environment
- Operating System: Windows
- Version: 11

**Comment by kitku2** [comment]
same issue, MilkShift?

**Comment by Milkshiift** [comment]
Looking into it. As a temporary fix you can disable "Script Loader" in the GoofCord settings. Be aware that it also disables dynamic icon, message encryption and invidious embeds

**Comment by Milkshiift** [comment]
Fixed in https://github.com/Milkshiift/GoofCord-Scripts/commit/31e63a1dc8c4c6c4c4ae99d890c3b45ef7d9d977
Fully restart GoofCord 2 times and screensharing should work
