### ISSUE TITLE
[BUG] Goofcord doesn't properly focus window when clicking on a notification (GNOME 46)

### ISSUE THREAD

**Issue by nyabinary** [Milkshiift/GoofCord#26]
### Description
Clicking on notifications doesn't focus the Goofcord window. 

### Steps to Reproduce
[List the steps to reproduce the bug]
Be on GNOME 46 (Wayland), click a notification, see that it doesn't focus Goofcord.

### Expected Behavior
That it does focus Goofcord.

### Actual Behavior
It doesn't focus Goofcord (another notification pops up and which is then clicked on to focus the windows, this makes focusing the windows take clicking on 2 separate notifications.)

### Screenshots
![image](https://github.com/Milkshiift/GoofCord/assets/97130632/bed4323a-35bb-40a8-9d7d-004ade4bf4d1) 2nd notification that pops up (and actually does focus the screen)

### Environment
- Operating System: NixOS 24.11
- Version: 1.4.3

### Additional Information
[Provide any additional information that might be useful in solving the problem, such as error messages or relevant logs]

**Comment by Milkshiift** [comment]
Clean GNOME 46 install, AppImage release, can't reproduce. Does anyone else experience the same problem?

**Comment by nyabinary** [comment]
Fixed suddenly :P
