### ISSUE TITLE
[BUG] goofcord killed by SIGSEGV

### ISSUE THREAD

**Issue by fisuri** [Milkshiift/GoofCord#27]
### Description
goofcord killed by SIGSEGV

### Steps to Reproduce
just using

### Expected Behavior
normal operation of the program

### Actual Behavior
goofcord killed by SIGSEGV

### Environment
- Operating System: Fedora Workstation 40
- Version: 1.4.3 (flatpak)

### Additional Information
https://pastebin.com/A9VzDHYR

**Comment by Milkshiift** [comment]
- Did you try reinstalling?
- Does this happen in the AppImage build?
The logs aren't very helpful :cry:

**Comment by fisuri** [comment]
> * Did you try reinstalling?
No, it happened only 1 time and without consequences.

> * Does this happen in the AppImage build?
No

**Comment by Milkshiift** [comment]
This doesn't seem to be an issue then if it happened only once and you can use GoofCord like normal
