### ISSUE TITLE
[BUG] Application not shutting down

### ISSUE THREAD

**Issue by Dodge100** [Milkshiift/GoofCord#28]
### Description
When trying to shut down application, application is unresponsive

### Steps to Reproduce
1. Open GoofCord
2. Close all windows
3. Long press on application at bottom navbar
4. In the popup, navigate to shut down and let go

### Expected Behavior
Application should do one of two things:
1. Application shuts down
2. Application doesn't shut down but instead says that it isn't responding and requires to be force quit. Upon force quitting, it will shut down.

### Actual Behavior
Does not shut down but doesn't say that application has to be force quit. Only way to close it to open macOS's version of task manager with ⌘ + ⌥ + esc. Doing so force quits the application and allows it to shut down.

### Environment
- Operating System: macOS 14.5
- Version: 1.4.3

**Comment by Milkshiift** [comment]
Does the same happen with "Minimize to tray" setting disabled?

**Comment by Dodge100** [comment]
with "Minimize to tray" disabled, the whole application shuts down when closing the window.

**Comment by Milkshiift** [comment]
Should be fixed in https://github.com/Milkshiift/GoofCord/commit/2b4c370305228691c4c60b630f42f7fe4562d41b

**Comment by Dodge100** [comment]
Reopened as of 1.5.1

**Comment by 9ineven** [comment]
Application doesn't shut down. Version 1.8.1. Flatpak.

**Comment by Arsconyl** [comment]
Application doesn't shutdown. Version 2.2.0. MacOS.

**Comment by Milkshiift** [comment]
@Arsconyl Can you share more details? How exactly are you closing it? Do you have "Minimize to tray" enabled?

**Comment by Arsconyl** [comment]
I tried multiple things and I discovered that the app closes well with ⌘+Q or quit option in app menu (whatever if "Minimize to tray" enabled or not) BUT it doesn't when clicking on quit with right-click menu on dock icon (whatever if "Minimize to tray" enabled or not) (this one):
<img width="195" height="378" alt="Image" src="https://github.com/user-attachments/assets/b7c0c32a-021f-433d-9a2a-ba989b9db5b8" />
