### ISSUE TITLE
[BUG] Encryption Error

### ISSUE THREAD

**Issue by XenoRaijin** [Milkshiift/GoofCord#29]
### Description
Encryption password does not seem to either be saved or read, resulting in the feature not working. This is the first time filling out a bug report so I apologize if any info is missing.

### Steps to Reproduce
1. Navigate to Goofcord settings via settings menu or tray icon
2. Enable "Message encryption"
3. Type in a password
4. Leave encryption cover/mark blank
5. Exit the settings window
6. Hit `Ctrl+Shift+R` to refresh
7. Hit `F10` to enable encryption, lock icon appears
8. Type a test message into an empty group chat
9. Get `TypeError [ERR_INVALID_ARG_TYPE]: The "password" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, or DataView. Received undefined` _see screenshot below_

### Attempted Troubleshooting
- Manually entering a password into the settings json
  - `"messageEncryption":true,"encryptionPasswords":["test"]`
- Cycling between passwords with `F9` before attempting to send a message
- Entering a cover message and mark
- Disabling all vencord plugins 

These all end in the same result seen in step 9.

### Expected/Actual Behavior
After step 8 I assume an empty message composed of invisible characters should be sent. I have not utilized Stegcloak before so I'm not completely sure what is supposed to happen.

Additionally, whenever I attempt to set a password and exit the settings menu, when I return to settings it is no longer listed.

### Screenshots
![image](https://github.com/Milkshiift/GoofCord/assets/63035556/0b113a85-9f2f-4569-8543-18408eabbf9e)

### Environment
- Operating System: Linux Mint Linux Mint 21.3 Cinnamon 6.0.4
- App Version: Flatpak, 1.4.3 - Reactive Astatine
- Discord Info: stable 307392 (6818046) Vencord 5c05443 (Web) Chromium 124

**Comment by Milkshiift** [comment]
Already fixed here https://github.com/Milkshiift/GoofCord/commit/37cfcbb0bdfa82a288e317cc9d6a86ecdfb2ea8e#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3d for the next release
