### ISSUE TITLE
[BUG] Dynamic icon not working in Windows when GoofCord is pinned

### ISSUE THREAD

**Issue by Milkshiift** [Milkshiift/GoofCord#3]
When the 'Dynamic icon' option is enabled, the taskbar icon does not update or display pings when GoofCord is pinned. This issue appears to be related to an unreported Electron bug.

Temporary solution: Unpin GoofCord from the taskbar.

**Comment by Milkshiift** [comment]
dd626dd122d3aa98f2f92c25002d73a32678a37a fixes the issue and implements the dynamic icon feature properly

**Comment by fyndrkraze** [comment]
hey, I'm using windows 11 and this feature is still not working for me.
