### ISSUE TITLE
[BUG] Client Mods not loading on GoofCord

### ISSUE THREAD

**Issue by Dodge100** [Milkshiift/GoofCord#30]
### Description
Client Mods not loading on GoofCord

### Steps to Reproduce
v1.5.0
MacOS

### Expected Behavior
Settings section should have a place for client mods like vencord and shelter to appear.

### Actual Behavior
No extra settings menu, not even for GoofCord

### Environment
- Operating System: macOS
- Version: 1.5.0

**Comment by Milkshiift** [comment]
Try **redownloading** and reinstalling GoofCord

**Comment by Milkshiift** [comment]
And does restarting not help?

**Comment by Dodge100** [comment]
initially, neither of these worked. however, replacing the files with those of an older version then replacing the older files with a newer version fixed the issues.
