### ISSUE TITLE
[REQUEST] Suncord Compat

### ISSUE THREAD

**Issue by Dodge100** [Milkshiift/GoofCord#31]
### Description
suncord is a vencord fork with more plugins. potentially, combine suncord and equicord allowing to use all of their plugins

### Use Case
allows usage of Suncord plugins easily

**Comment by Dodge100** [comment]
here are some more popular vencord forks: https://github.com/Vendicated/Vencord/forks

**Comment by Milkshiift** [comment]
Added in https://github.com/Milkshiift/GoofCord/commit/eb8cdce08001fd876911a3e178b50c07a1249960

> potentially, combine suncord and equicord allowing to use all of their plugins

Vencord forks can't be combined (by GoofCord)
