### ISSUE TITLE
[BUG]  Encryption passwords not saved due to error in safeStorage.encryptString 

### ISSUE THREAD

**Issue by jmath3912** [Milkshiift/GoofCord#33]
### Description
When running the AppImage version of GoofCord 1.5.0 and going to the GoofCord settings to enable message encryption, encryption passwords do not actually get saved anywhere.

### Steps to Reproduce

1. Start GoofCord from the terminal via the AppImage file, keeping the terminal open
2. Navigate to the GoofCord settings (`Ctrl + Shift + '`)
3. Enable Message Encryption
4. Type a password in the "Encryption passwords" text box
5. Click outside of the text box to save your input, taking note of error messages printed in the terminal
6. Restart GoofCord and go back into the settings to confirm that the password did not get saved

### Expected Behavior
Following the steps above, one would expect the encryption passwords to be encrypted and saved to their respective location on the system.

### Actual Behavior
While monitoring the program output in the terminal, the following error message gets printed to the screen upon entering a password:

```
Error occurred in handler for 'encryptSafeStorage': Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
    at /tmp/.mount_GoofCo1eDO1i/resources/app.asar/ts-out/main.js:53:11535
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82871)
    at WebContents.emit (node:events:519:28)
```
It looks like the IPC handler for encryptSafeStorage fails at the call to encryptString because encryption is supposedly not available. I am unsure if this is a GoofCord issue or a system issue.

### Environment
- Operating System: Arch Linux
- GoofCord Version: 1.5.0

**Comment by Milkshiift** [comment]
The passwords are encrypted for storage using a system keyring. Unlike Windows and macOS, a Linux system does not always have an implementation of it, which the error tells you about.
Install `gnome-keyring` and encryption should start working. Most desktop environments have it installed by default.

**Comment by jmath3912** [comment]
That's the exact issue I'm having though. I've had gnome-keyring and libsecret (the replacement for libgnome-keyring) installed already, but even then I'm still running into the same "Encryption is not available" error.

**Comment by Milkshiift** [comment]
Still an environment issue. Some sort of misconfiguration, perhaps. Electron's documentation on safeStorage may be helpful https://www.electronjs.org/docs/latest/api/safe-storage
I can't provide much support for this since this is not directly a bug of GoofCord.

**Comment by Milkshiift** [comment]
Actually, this seems to be caused by flatpak sandboxing. On the same machine, flatpak version of GoofCord fails to save passwords, while non-flatpak successfully saves them

**Comment by Milkshiift** [comment]
Updated flatpak manifest with a fix https://github.com/flathub/io.github.milkshiift.GoofCord/commit/092ca9425337c72427603d2fe9a10bd6038324e0.
Update GoofCord and you should be able to save encryption passwords
