### ISSUE TITLE
[BUG] Videos can't be fullscreen

### ISSUE THREAD

**Issue by Tahinli** [Milkshiift/GoofCord#35]
### Description
Videos in channels can't be watched in fullscreen

### Steps to Reproduce
Try to make a video fullscreen

### Expected Behavior
Being fullscreen

### Actual Behavior
Not being fullscreen

### Screenshots
:D

### Environment
Fedora 40 KDE Plasma
Software Version 1.5.0

**Comment by Milkshiift** [comment]
Duplicate of https://github.com/Milkshiift/GoofCord/issues/32

**Comment by Tahinli** [comment]
Is flatpak version updated ?

**Comment by Milkshiift** [comment]
No, the update with the commit has not been released yet

**Comment by Tahinli** [comment]
Thanks
