### ISSUE TITLE
Clarification on privacy and security

### ISSUE THREAD

**Issue by Quotable8740** [Milkshiift/GoofCord#37]
I recently decided to give this client a chance from previously using Vesktop.

Immediately upon logging into the client, my IDS flagged and blocked a suspicious incoming request matching a Tor exit node.

![image](https://github.com/user-attachments/assets/ff0a41f3-ec7d-4cd3-95e5-74836d3a9e5a)

Could some clarity around this be given, I've never had my IDS triggered before with any other discord client, including  Vesktop and the official client.

- Flatpak version
- Brand new install of Fedora 40 with nothing other than Chrome, Steam and GoofCord installed.

Is this client creating tunnels using Tor?
Why are requests coming from an exit node?

https://spur.us/context/65.109.30.253

**Comment by Milkshiift** [comment]
All network related activity GoofCord does is:
1. Block unwanted requests 
2. Fetch client mods from GitHub
3. Fetch latest GoofCord release information from GitHub for update notifications    

Tor is not used in any way.
I highly doubt this has something to do with GoofCord directly. Can you replicate the same behaviour twice?

**Comment by cavdarfurkan** [comment]
I would appreciate if you could give an update on whether you reproduced the behavior or figured out it was caused by something else. @Quotable8740

**Comment by Quotable8740** [comment]
Apologies, I meant to get back to this - It seems like this is a false positive due to the underlying provider that Ubiquiti uses for IDS signatures.

It seems like at some point, this IP was used as a TOR exit node and it is still falsely identified as one even though it is a data-centre and likely where some of the client mods are hosted (CDN?)

For some reason more recently, outgoing requests have been getting incorrectly flagged when receiving a response from the server (I've had an uptick of normal requests being flagged after this).


Apologies for the waste of time.
