### ISSUE TITLE
[BUG] Screen Tearing

### ISSUE THREAD

**Issue by Tahinli** [Milkshiift/GoofCord#38]
- [x] I have searched and found no existing issues on the same topic

### Description
Screen tearing happens on top of screen when I share my screen
### Steps to Reproduce
share your screen
### Expected Behavior
tearing shouldn't be happened
### Actual Behavior
tearing is happening
### Screenshots
I can't share because when I want to record with obs, it's not happening.
### Environment
Fedora 40 | KDE Plasma | x11
x86_64
GoofCord version: 1.5.1

**Comment by Milkshiift** [comment]
Is tearing happening only inside a stream, or on screen globally?
What screen tearing are you talking about exactly? Like, lack of vertical synchronization type tearing?
Does tearing stop when the stream is stopped?

**Comment by Tahinli** [comment]
> Is tearing happening only inside a stream, or on screen globally? What screen tearing are you talking about exactly? Like, lack of vertical synchronization type tearing? Try recording with another software or externally, video of the tearing would be very handy. Does tearing stop when the stream is stopped?

It's only happening in stream. I personally can not see it but my friends can see it in my stream.

**Comment by Milkshiift** [comment]
So, you are talking about this https://github.com/Milkshiift/GoofCord/wiki/FAQ#laggy-screensharestream
And good news is I recently got it fixed for most scenarios https://github.com/Milkshiift/GoofCord/commit/bab1606fbba758d20e5f9857b256945a0192b13c
I'm closing this issue. If you still experience the same problem after I release an update, let me know.

**Comment by Tahinli** [comment]
https://github.com/user-attachments/assets/048d05f9-b8b7-4a22-b7a3-8a5a3599e7ec

I think it's not solved. I started a stream and my friend was watching my stream and I recorded it with my phone. This technic I think helps to show a problem more clearly then normal recording, because it's mirroring by other stream.
