### ISSUE TITLE
[BUG] suncord merged into equicord

### ISSUE THREAD

**Issue by sudosign** [Milkshiift/GoofCord#39]
ik u just added suncord but they recently sunsetted and are being basically merged into equicord https://github.com/verticalsync/Suncord

> Use [Equicord](https://github.com/Equicord/Equicord) now. Suncord has gone EOL. Because I don't always have the time to keep up with what people suggest or such and it's easier for me to work on [Equicord](https://github.com/Equicord/Equicord) with other people, the source and everything will stay here and you can still use it, but it'll probably become outdated after some time and break.

not sure if u want to keep but wanted to point it out

**Comment by Milkshiift** [comment]
Removed it already https://github.com/Milkshiift/GoofCord/commit/5e31248703da3e0f4b2bd98fb0e0ce856f216f24
