### ISSUE TITLE
Build GoodCord on macOS

### ISSUE THREAD

**Issue by jacksongoode** [Milkshiift/GoofCord#4]
https://github.com/Milkshiift/GoofCord/blob/918c75d9ec4df1acd56ea84f1447dc31a55f8d02/src/content/css/titlebar.css#L239

Since it's been supported in the recent release of ArmCord (see https://github.com/ArmCord/ArmCord/commit/bcb54b4f793d14acd195a3efed0e82fc940b770d) I would think it might be easy to build Goof as well?

I hope so!

**Comment by Milkshiift** [comment]
It's not that straightforward sadly. I don't have a macOS device so I can't test the app at all. If I had someone who can test it, it would be much easier. 
In the upcoming update, I will try to implement an alpha-level macOS support.

Added to the [Roadmap](https://github.com/Milkshiift/GoofCord/wiki/Roadmap)

I'll be keeping this issue open to provide updates on the progress of macOS support.

**Comment by jacksongoode** [comment]
Would really be excited to see this given that ArmCord development has slowed.

**Comment by Milkshiift** [comment]
Added macOS support, I hope it at least launches 😬

**Comment by jacksongoode** [comment]
Trying it now!

**Comment by jacksongoode** [comment]
Or I'll try it once a build is release!

**Comment by Milkshiift** [comment]
I can publish a pre-release with macos build

**Comment by Milkshiift** [comment]
https://github.com/Milkshiift/GoofCord/releases/tag/v1.0.0 Here

**Comment by Milkshiift** [comment]
it's a pre-release so things will be buggy

**Comment by jacksongoode** [comment]
Hmm, appears to be running under Intel on my arm Macbook. Maybe it built incorrectly.

**Comment by jacksongoode** [comment]
Hmm, appears to be running under Intel on my arm Macbook. Maybe it built incorrectly.

**Comment by Milkshiift** [comment]
I think I know what's the issue. I will notify you when I rebuild with a fix

**Comment by jacksongoode** [comment]
Thanks!

**Comment by Milkshiift** [comment]
Made a new release with macOS support. You need to download the arm64 dmg file. Hope it works for you. Also, can you, if possible, screenshot the titlebar and attach it here? I'm not sure it shows up as expected. Thanks.

**Comment by jacksongoode** [comment]
<img width="705" alt="image" src="https://github.com/Milkshiift/GoofCord/assets/54308792/33961706-086f-4f2b-bd7a-c0174e6ff69b">

It runs on my end! The title bar is quite wonky tho 🤭

**Comment by Milkshiift** [comment]
Fixed it. Should be normal in the next update
