### ISSUE TITLE
[REQUEST] YouTube adblock

### ISSUE THREAD

**Issue by SaltySP** [Milkshiift/GoofCord#40]
The YouTubeAdblock plugin shows up but can not be used in Goofcord.

Search for YouTubeAdblock in Vencord>Plugins

![image](https://github.com/user-attachments/assets/0a2f2543-6ac0-4675-bc2c-a24bb5e51a97)

Unsure if this is bug or intended.

### Environment
- Windows 11 23H2
- x64
- GoofCord Version: 1.5.1

**Comment by Milkshiift** [comment]
This is an issue with Vencord, the plugin is made in a way that makes it work only in the official client or in Vesktop.
I will try to port functionality of the plugin to GoofCord, adblock seems like a fitting thing for GoofCord to have out of the box

**Comment by Milkshiift** [comment]
Added in https://github.com/Milkshiift/GoofCord/commit/569acb6cebe5b61935792e79b0058dd69409f107
