### ISSUE TITLE
[REQUEST] Option to choose YouTube provider/backend in settings

### ISSUE THREAD

**Issue by nyabinary** [Milkshiift/GoofCord#41]
- [x] I have searched and found no existing issues on the same topic

I want to choose between the native YouTube backend and the Invidious backend in Goofcord settings :P

**Comment by Milkshiift** [comment]
For now, you can disable "Invidious Embeds" shelter plugin to use default YouTube embeds

**Comment by Milkshiift** [comment]
Added in https://github.com/Milkshiift/GoofCord/commit/747cdfbe91bc582c52aefbdb1266d6371a687b24 & https://github.com/Milkshiift/goofcord-shelter-plugins/commit/8d6131c85c5718ab12d699ded20f080c975d6df7
