### ISSUE TITLE
[REQUEST] Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [Milkshiift/GoofCord#47]
- [X] I have searched and found no existing issues on the same topic

### Description
Since major distros like Linux Mint and Elementary OS are hiding or discouraging unverifued flatpaks, if will be harder for people on these operating systems to find GoofCord

### Additional context
Here's a link to Flathub's verification documentation https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by Milkshiift** [comment]
Verified
