### ISSUE TITLE
[BUG] Encrpytion Password is never stored

### ISSUE THREAD

**Issue by ZachDavies** [Milkshiift/GoofCord#48]
- [x] I have searched and found no existing issues on the same topic
- [x] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Description
I open the goofcord settings, enable message encryption, enter a password, cover message.
then ctrl shift r to restart. After restart, when opening the settings the cover message is there, message encrpytion is still on but the password is gone and when i try to use the message encryption i get an error

TypeError [ERR_INVALID_ARG_TYPE] The "password" argument must be of type string  or an instance of Arraybuffer, Buffer, TypedArray, or Dataview. Recieved undefined

### Steps to Reproduce

Enter a encryption password, restart goofcord, enable message encryption in a chat and send a message.

### Expected Behavior

Enabling message encryption in the chat, send a message and an encrypted message using the provided password is sent

### Actual Behavior

Error on sending message

TypeError [ERR_INVALID_ARG_TYPE] The "password" argument must be of type string  or an instance of Arraybuffer, Buffer, TypedArray, or Dataview. Recieved undefined

### Screenshots

![2024-08-22_09-30](https://github.com/user-attachments/assets/60cf2e72-36a5-4cc3-8c12-c34c65273782)

### Environment
- Operating System (name and version): Arch 6.10.6
- GoofCord Version: 1.6.0

**Comment by Milkshiift** [comment]
Open GoofCord in a terminal, try to save the passwords and share the logs

**Comment by ZachDavies** [comment]
Process execution path: /usr/lib/electron31/electron
[Firewall] Set up CSP unstricter
[Firewall] Firewall initialized
[Message Encryption] Loaded encryption passwords
[Script Loader] Categorized scripts
[Mod Loader] Loaded extension: shelter
[Mod Loader] Loaded extension: vencord
[Timer] GoofCord fully loaded in: 210.541ms
[Mod Loader] Downloading mod bundles for: vencord
[124898:0822/095415.287206:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[Mod Loader] Bundles downloaded for: vencord
[Mod Loader] Downloading mod bundles for: shelter
[Mod Loader] Bundles downloaded for: shelter
Creating a settings window.
Error occurred in handler for 'encryptSafeStorage': Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
    at /usr/lib/goofcord/app.asar/ts-out/main.js:51:11573
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83553)
    at WebContents.emit (node:events:519:28)

**Comment by ZachDavies** [comment]
I got gnome-keyring still resulting with this issue in logs,

Creating a settings window.
Error occurred in handler for 'encryptSafeStorage': Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
    at /usr/lib/goofcord/app.asar/ts-out/main.js:51:11573
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83553)
    at WebContents.emit (node:events:519:28)

**Comment by Milkshiift** [comment]
You also need libsecret probably. And maybe a restart

**Comment by ZachDavies** [comment]
already had libsecret, did a restart, still same error

[Mod Loader] Bundles downloaded for: shelter
Error occurred in handler for 'encryptSafeStorage': Error: Error while encrypting the text provided to safeStorage.encryptString. Encryption is not available.
    at /usr/lib/goofcord/app.asar/ts-out/main.js:51:11573
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:83553)
    at WebContents.emit (node:events:519:28)

**Comment by Milkshiift** [comment]
Try running GoofCord with `--password-store="gnome-libsecret"`

**Comment by ZachDavies** [comment]
that argument worked for my friend, but when i did it after entering a password, goofcord hung

**Comment by ZachDavies** [comment]
now its not crashing but after entering a password, nothing happens in the logs and no password is saved.

**Comment by ZachDavies** [comment]
Its working now using --password-store="gnome-libsecret", thanks :)

**Comment by Milkshiift** [comment]
Great :+1:

**Comment by ZachDavies** [comment]
is there a way to make goofcord automatically set the password store? as opening goofcord normally now breaks the encryption

**Comment by Milkshiift** [comment]
If you are using the flatpak version, you can set custom launch arguments in flatseal.
In AUR version, you can modify goofcord.sh from the package to set the password store.
Otherwise, you need to create or modify GoofCord's .desktop file to include the argument.

**Comment by ZachDavies** [comment]
I found the goofcord.sh, what do i change to set the password store.

file:

#!/bin/bash
set -o pipefail
_APPDIR="/usr/lib/@appname@"
_RUNNAME="${_APPDIR}/@runname@"
_CFGDIR="@cfgdirname@/"
_OPTIONS="@options@"
export PATH="${_APPDIR}:${PATH}"
export LD_LIBRARY_PATH="${_APPDIR}/swiftshader:${_APPDIR}/lib:${LD_LIBRARY_PATH}"
export ELECTRON_IS_DEV=0
export ELECTRON_FORCE_IS_PACKAGED=true
export ELECTRON_DISABLE_SECURITY_WARNINGS=true
export ELECTRON_OVERRIDE_DIST_PATH="/usr/bin/electron@electronversion@"
export NODE_ENV=production
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export _FLAGS_FILE="${XDG_CONFIG_HOME}/${_CFGDIR}@appname@-flags.conf"
declare -a _USER_FLAGS
if [[ -f "${_FLAGS_FILE}" ]]; then
    while read -r line; do
        if [[ ! "${line}" =~ ^[[:space:]]*#.* ]]; then
            _USER_FLAGS+=("${line}")
        fi
    done < "${_FLAGS_FILE}"
fi
cd "${_APPDIR}"
if [[ "${EUID}" -ne 0 ]] || [[ "${ELECTRON_RUN_AS_NODE}" ]]; then
    exec electron@electronversion@ "${_RUNNAME}" ${_OPTIONS} "${_USER_FLAGS[@]}" "$@"
else
    exec electron@electronversion@ "${_RUNNAME}" ${_OPTIONS} --no-sandbox "${_USER_FLAGS[@]}" "$@"
fi

**Comment by Milkshiift** [comment]
Change last 4 lines
```
if [[ "${EUID}" -ne 0 ]] || [[ "${ELECTRON_RUN_AS_NODE}" ]]; then
    exec electron@electronversion@ "${_RUNNAME}" ${_OPTIONS} "${_USER_FLAGS[@]}" --password-store="gnome-libsecret" "$@"
else
    exec electron@electronversion@ "${_RUNNAME}" ${_OPTIONS} --password-store="gnome-libsecret" --no-sandbox "${_USER_FLAGS[@]}" "$@"
fi
```

**Comment by Milkshiift** [comment]
Cool. Though be warned that if you enable "Launch GoofCord on startup" option it will not start with the correct arguments as it skips the desktop file. You'll need to modify .desktop in ~/.config/autostart/ too.
