### ISSUE TITLE
[BUG] macOS task bar icon is huge

### ISSUE THREAD

**Issue by jacksongoode** [Milkshiift/GoofCord#5]
<img width="598" alt="image" src="https://github.com/Milkshiift/GoofCord/assets/54308792/e7e8f1f4-c794-4e64-9704-16148b7e8e67">

On 1.0.1

**Comment by Milkshiift** [comment]
Was this problem present in the previous version (1.0.0)?

**Comment by Milkshiift** [comment]
Never mind, I think I fixed it
