### ISSUE TITLE
[REQUEST] Localization

### ISSUE THREAD

**Issue by olivertzeng** [Milkshiift/GoofCord#50]
- [x] I have searched and found no existing issues on the same topic

### Description
I would like to translate GoofCord to zh_TW but GoofCord might need to implement a method to provide localizations(like .po)

### Use Case
If there are people who doesn't speak English, or just want to see GoofCord in their language like me, then this is for them!

### Describe alternatives you've considered
none

### Additional context
idk

**Comment by Wuemeli** [comment]
smth like Crowdin?

**Comment by olivertzeng** [comment]
> smth like Crowdin?

doesn't need to be that fancy though
can be a text file, json, lproj or whatever fits

**Comment by olivertzeng** [comment]
> I think Crowdin would be great, actually. I'll see what I can do

Nice

**Comment by comradekingu** [comment]
@Milkshiift Weblate is vastly superior for translators, and it doesn't have egregious terms and services.
https://hosted.weblate.org/hosting/  :)

**Comment by Milkshiift** [comment]
Yes that's what I'll use

**Comment by olivertzeng** [comment]
> Yes that's what I'll use

tbh I prefer crowdin because it doesn't have confusing interfaces and provides issue reporting such as requests for context and stuff
but weblate is fine if you want

https://tolgee.io/ tolgee is another cool one that I've never use but recommend it because it looks sleek and is open source
there are a lot of options out there

**Comment by comradekingu** [comment]
@olivertzeng I think he meant Weblate will be used.
There aren't a lot of libre software options. Pontoon takes inspiration from Crowdin, so it has the same broken functionality. RedHat closed Zanata in favour of Weblate.
Pootle is dormant.

I have extensive experience in nearly all the platforms, and I will make sure to check out Tolgee, which I hadn't heard of.
Thank you :)

**Comment by Wuemeli** [comment]
Hey @olivertzeng,

You can now translate GoofCord: https://hosted.weblate.org/projects/goofcord/goofcord/

**Comment by Milkshiift** [comment]
You can, but you shouldn't before the update. The translation strings might still change and there is no practical reference for new strings since 1.6.0 unless you want to build GoofCord from source.

**Comment by Milkshiift** [comment]
I locked the weblate component for now.

Localization is technically implemented in the client, but the next release will ship without any translations or ways to change the locale. Only the release after that will actually have everything working.

Weblate also needs to approve GoofCord for free libre hosting

**Comment by Milkshiift** [comment]
You can translate GoofCord at https://hosted.weblate.org/projects/goofcord/goofcord
Your translations will be available in the next release

**Comment by olivertzeng** [comment]
Neat! Will do
