### ISSUE TITLE
[REQUEST] PTT on unfocused window

### ISSUE THREAD

**Issue by VirtualJunky** [Milkshiift/GoofCord#52]
- [x] I have searched and found no existing issues on the same topic

### Description
Allowing Push To Talk (PTT) when the window isn't in focus.

### Use Case
Using PTT when working, playing games or other activities that require window focus to be elsewhere.

### Describe alternatives you've considered
1) [This](https://github.com/tuxinal/venbind), which I found via [this](https://github.com/Vencord/Vesktop/pull/326). No idea how to implement that though personally.
2) [Push2Talk](https://github.com/cyrinux/push2talk) for Pipewire, but I don't want system wide muting to fix one application.
3) Using normal Discord :(

### Additional context
Pop!_OS, X11, Gnome, every thing is up to date.

**Comment by VirtualJunky** [comment]
Ah my apologies, I've never used the keybinds tab in settings, only ever the PTT in the voice settings, so I only searched for PTT or "push to talk" in some variations to see if an issue was already up and didn't see any.

**Comment by Milkshiift** [comment]
Oh it's absolutely fine, the other issue wasn't about PTT specifically and it's logical to think it's a separate problem. But since they share a common possible solution, it would be better to discuss everything in one place
