### ISSUE TITLE
[BUG] Posting YouTube link with Invidious embeds enabled shows embed twice.

### ISSUE THREAD

**Issue by nyabinary** [Milkshiift/GoofCord#54]
- [x] I have searched and found no existing issues on the same topic
- [x] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Steps to Reproduce
Send a YouTube link with Invidious embeds enabled.

### Expected Behavior
It'll send an embed once, not twice.

### Actual Behavior
It sends an embed twice.

### Screenshots
![image](https://github.com/user-attachments/assets/e1e202a0-3c22-43f0-b9c7-71f6e42574d2)

### Environment
- Operating System NixOS-unstable
- GoofCord Version: 1.6.0
- Way of installing: nixpkgs

**Comment by Milkshiift** [comment]
Should be fixed in https://github.com/Milkshiift/goofcord-shelter-plugins/commit/60b42f32590923a134e3bf67210ac9f7ea36e9ea
