### ISSUE TITLE
[BUG] [Linux] Screen sharing stutter/bad quality when audio shared, too

### ISSUE THREAD

**Issue by Milliw** [Milkshiift/GoofCord#56]
- [x] I have searched and found no existing issues on the same topic
- [x] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

Hi! First, thanks for this awesome piece of software!
### Description
When screen sharing with audio share, something is failing because quality gets really bad.
Without audio sharing, I can see my gpu using its video encoder and with audio it is not. No matter if I share game or whole display. Also upload rate is way more without sound (~2-4 MB/s) than with sound (~200-400 KB/s).

### Steps to Reproduce
Share game (steam, proton) with audio enabled

### Environment
- Operating System (name and version): Nobara 40 Gnome Edition
- GoofCord Version: 1.6.0 (according to gnome software)
- Way of installing: Flatpak

### Additional Information
Wayland, AMD RX 6700
I used Vesktop for quite a while and on their github they mention some issue within Electron which will be fixed after using Electron 32. Which one is Goofcord on atm?

### What I tried
Changing sharing method from app to display.
Ensuring, Goofcord is using wayland (by xwininfo cmd).

**Comment by Milkshiift** [comment]
1.6.0 uses Electron 31, next release will use 32. I think you should retest this when the next version comes out before any investigation is done

**Comment by Milkshiift** [comment]
I've found a Vesktop issue on the same topic: https://github.com/Vencord/Vesktop/issues/528
Seems like nothing can be done on GoofCord's side to fix this, therefore closing as not planned

**Comment by Milliw** [comment]
When will next version come out?
It's not THAT important to me. I also had some issues Goofcord crashing/restarting itself similar to the other newly created bug report. Again - not that big of an issue for me as I do have other DC clients installed as well. But if welcome I will do my best to support by sending logs, doing tests or similar. But compiling myself without detailed instructions is beyond my skills. =)

**Comment by Milliw** [comment]
> I've found a Vesktop issue on the same topic: [Vencord/Vesktop#528](https://github.com/Vencord/Vesktop/issues/528) Seems like nothing can be done on GoofCord's side to fix this, therefore closing as not planned

I understand. But as you close this issue, no one will recognise it so maybe at least mention it somewhere so people know about it. I've read your linked issue and to me it does not sound like next electron version will fix this.
