### ISSUE TITLE
[BUG] application repeatedly force closed and rejoined the call while screen sharing

### ISSUE THREAD

**Issue by Carthaigh-byte** [Milkshiift/GoofCord#57]
I have searched and found no existing issues on the same topic
I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

Description

While screen sharing on Discord, the application repeatedly force closed and rejoined the call until I completely shut it down. Upon restarting, the same issue persisted.

Steps to Reproduce
Start a Discord call.
Begin screen sharing.
Observe the application force closing and rejoining the call repeatedly.

Expected Behaviour
The application should allow continuous screen sharing without force closing or disconnecting from the call.

Actual Behaviour
The application force closes and re-joins the Discord call repeatedly, making it impossible to maintain a stable connection.

Environment
Operating System (name and version): Fedora Linux 40 (Budgie) x86_64

**Comment by Milkshiift** [comment]
Are you getting disconnected from the call, or is GoofCord closing? Does this happen in other clients (official web, desktop)?
Try disabling every client mod in the settings and joining a call

**Comment by Carthaigh-byte** [comment]
This does not happen in the offical Discord client. I have tested this out. It exits the call, Goofcord eventually closed.

**Comment by Milkshiift** [comment]
Open GoofCord from console and share logs after it closes

**Comment by Milkshiift** [comment]
Does this still happen?
