### ISSUE TITLE
[REQUEST] Raise users' volume above 100%

### ISSUE THREAD

**Issue by Foresteam** [Milkshiift/GoofCord#59]
- [x] I have searched and found no existing issues on the same topic

### Description
Raise users' volume above 100%, like you can in the official client
### Use Case
Windows, where you can't raise app's volume above 100%
### Describe alternatives you've considered
Just use linux? :)
Or play around with system volume, in different ways

**Comment by nyabinary** [comment]
> I think there's a Vencord Plugin for that

Yeah VolumeBooster
