### ISSUE TITLE
[REQUEST] Integrate OpenAsar custom app.asar for faster startup

### ISSUE THREAD

**Issue by jacksongoode** [Milkshiift/GoofCord#6]
Unless there is some compatibility issues with this...

**Comment by Milkshiift** [comment]
It's impossible. GoofCord is completely standalone from original Discord. ".asar" file holds all code of an electron app, you can't just replace GoofCord code with Discord code. Plus GoofCord opens as fast as Discord with OpenAsar does, or probably even faster.
GoofCord just loads a browser version of Discord, so it doesn't need to do much stuff
