### ISSUE TITLE
[REQUEST] Symbolic tray icon

### ISSUE THREAD

**Issue by EPOCHvoyager** [Milkshiift/GoofCord#63]
- [x] I have searched and found no existing issues on the same topic

### Description
While the current tray icon is functional, a simpler looking alternative would be much appreciated.
### Use Case
Desktop environments like GNOME heavily favor the use of monochrome symbolic icons on the main panel, so it would make GoofCord fit better in that use case. It'd also be easier to scale down while maintaining legibility, which is important for lower resolution displays in the small space reserved for system trays.
### Describe alternatives you've considered
For the GNOME use case I've described, there are extensions like [Desaturated Tray icons](https://github.com/CR1337/desaturated-tray-icons), or manually lowering saturation in the AppIndicator extension settings. However, that's of course not a symbolic icon. There's also the alternative of setting a custom tray icon inside the GoofCord settings, but that does not work with the dynamic icon enabled for notifications at a glance, nor is there a readily available one with the GoofCord logo.
### Additional context
Depending on the implementation, the ability to manually select a light or dark variant might be a good idea.

**Comment by Milkshiift** [comment]
Kind of added in https://github.com/Milkshiift/GoofCord/commit/64e72a511c89f4c140405f41c4b5a431a348b881
For now, I’m not planning to add a dedicated option for tray icon selection, as the settings are already cluttered, and custom icon selection covers most use cases. Adding both would feel redundant.
You will need to change the setting manually:
1. Open the GoofCord folder (using the settings button or `.config/goofcord/GoofCord`)
2. Open settings.json
3. Change value of `trayIcon` to either `gf_symbolic_white.png` or `gf_symbolic_black.png`

I'm not sure the [icon](https://github.com/Milkshiift/GoofCord/blob/main/assetsDev/gf_symbolic.svg) is the best it could be and fits other symbolic icons, so if you think you could improve it, feel free to open a pr
