### ISSUE TITLE
[BUG] SUID sandbox helper binary not configured correctly

### ISSUE THREAD

**Issue by JaredTamana** [Milkshiift/GoofCord#69]
- [ * ] I have searched and found no existing issues on the same topic
- [ * ] I have searched the [wiki](https://github.com/Milkshiift/GoofCord/wiki/FAQ) and found no mention of my problem

### Description
The x86 AppImage produces the following error on execution:
```
[8738:0929/010517.020939:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_GoofCofqoCQT/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

### Steps to Reproduce
- `chmod +x GoofCord-1.7.1-linux-x86_64.AppImage`
- `./GoofCord-1.7.1-linux-x86_64.AppImage`

### Expected Behavior
Launch app.

### Actual Behavior
Crashed, core dumped.

### Environment
- Operating System: 
  - Ubuntu 24.04.1 LTS
  - Kernel: Linux 6.8.0-45-generic
  - Architecture: x86-64

- GoofCord Version: 1.7.0 and 1.7.1
- Way of installing: AppImage (no x86 .deb prebuilt)

### Additional Information
If there was a .deb x86-64 package, I would use this instead, but this architecture seems to be left out of the prebuilt releases.

**Comment by JaredTamana** [comment]
Electron issue: https://github.com/electron/electron/issues/17972

**Comment by Milkshiift** [comment]
This is not a GoofCord issue directly. Possible workarounds are in the issue you linked.
Also, x86-64 .deb _is_ pre-built, under the name "GoofCord-1.7.1-linux-amd64.deb"
