### ISSUE TITLE
[BUG] MacOS arm-64 .dmg repported as "damaged"

### ISSUE THREAD

**Issue by nescapp** [Milkshiift/GoofCord#7]
### Description
When trying to open, getting error "GoofCord is damaged and can't be opened" on MacOS running on Apple's M2 Chip

### Steps to Reproduce
Try to install on MacOS running on Apple's M2 Chip

### Expected Behavior
Opens normally

### Actual Behavior
Shows error "GoofCord is damaged and can't be opened"

### Screenshots
<img width="269" alt="image" src="https://github.com/Milkshiift/GoofCord/assets/97590612/ee4204e3-4424-41d3-a24e-be57a3689cd9">

### Environment
- Operating System: macOS 14.2 (Sonoma)
- Version: 1.1.0
- Chip: Apple M2

### Additional info
This is strictly an issue with the arm-64 .dmg, the x64 .dmg is fine

**Comment by Milkshiift** [comment]
According to online sources the "error" is shown due to security measures in macOS.
You can try following [this](https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/) article to remove GoofCord from quarantine.

**Comment by nescapp** [comment]
Right. I forgot MacOS was so stupid. Thank you
