### ISSUE TITLE
[BUG] Generated checksum for "electron-v32.2.3-win32-x64.zip" did not match expected checksum.

### ISSUE THREAD

**Issue by celisej567** [Milkshiift/GoofCord#75]
While installing dependencies ive got an error: 
 
![изображение](https://github.com/user-attachments/assets/be8be04a-c290-4742-b428-af26741e01ab)

### Environment
- Operating System: Windows 11 23H2
- GoofCord Version: latest at the moment
- Way of installing: Building from source

**Comment by Milkshiift** [comment]
Not related to GoofCord directly. There are many reports and potential solutions for this on the internet

**Comment by celisej567** [comment]
Ok i think ill close this issue then.

**Comment by Milkshiift** [comment]
If you have not found a solution yet, or for anyone looking for it:
You also need to install Node.js, not only Bun.
