### ISSUE TITLE
[REQUEST] Make it compatible with BetterDiscord plugins

### ISSUE THREAD

**Issue by ddd75a650fee04c0ce576c877521c6bd** [Milkshiift/GoofCord#79]
Set it by default like Vencord or make it compatible with BetterDiscord, just like the default Discord client.
There's much more plugins made for BetterDiscord, some of them are very unique, like the one that let you set a local password to your Discord client.

**Comment by Milkshiift** [comment]
GoofCord uses the web version of Discord, which BetterDiscord doesn't support. There have been attempts to add BD support for LegCord, and there is an [extension](https://github.com/tsukasa/BdBrowser) for browser support, but nothing GoofCord can use right now. I'm not personally interested in finding a way to make BD compatible with web either
