### ISSUE TITLE
[BUG] Invidious replacement iframe overshooting frame

### ISSUE THREAD

**Issue by jacksongoode** [Milkshiift/GoofCord#9]
### Description
It seems that the Invidious instance that replaces the YouTube player extends past the frame of the existing video player. This makes the fullscreen button hidden.

Guessing some additional css props might need to be added here: https://github.com/Milkshiift/GoofCord-Scripts/blob/main/patches/BL12_invidiousEmbeds.js

### Steps to Reproduce
Play a video with Invidious replaced.

### Expected Behavior
Replacement video player should fit the same player size.

### Actual Behavior
Frame is underfitted.

### Screenshots
<img width="413" alt="image" src="https://github.com/Milkshiift/GoofCord/assets/54308792/0cdf9688-a421-4c7b-8657-f63c61a5e7fa">

### Environment
- Operating System: macOS 13.5
- Version: 1.2.0

**Comment by Milkshiift** [comment]
This is rather a problem in the library that Invidious uses for its embeds ― video.js, that doesn't do the scaling properly. The invidious controls bar is also pretty bloated with useless buttons for an embed.
 While it's theoretically feasible to address this on GoofCord's side with CSS, the only way I can think of to do this is to constantly scan the DOM for the Invidious iframe and inject CSS into it, which will hurt performance and is a bad solution overall.
Will probably never get fixed unless I find a better way to inject CSS into iframes
